version: "3.8"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: izzzi
      POSTGRES_USER: izzzi
      POSTGRES_PASSWORD: izzzi
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - izzzi-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U izzzi -d izzzi"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0

  redis:
    image: redis:7-alpine
    networks:
      - izzzi-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0

  backend:
    image: izzzi/backend:latest
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://izzzi:izzzi@postgres:5432/izzzi
      REDIS_URL: redis://redis:6379
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: "587"
      FRONTEND_URL: http://167.99.135.132
    networks:
      - izzzi-network
    depends_on:
      - postgres
      - redis
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:4000/api/health"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 60s

  frontend:
    image: izzzi/frontend:latest
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE_URL: http://167.99.135.132/api
    networks:
      - izzzi-network
    depends_on:
      - backend
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 60s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - izzzi-network
    depends_on:
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - izzzi-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  izzzi-network:
    driver: overlay
    attachable: true

volumes:
  pgdata:
    driver: local
