#cloud-config
# Cloud-init configuration for IZZZI Docker Compose deployment
# Generated by Terraform

users:
  - name: deploy
    groups: sudo, docker
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ${ssh_public_key}

# Update system packages
package_update: true
package_upgrade: true

# Install base packages
packages:
  - curl
  - htop
  - vim
  - git
  - jq
  - postgresql-client
  - ufw
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release

# Write files
write_files:
  - path: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "3"
        }
      }
    owner: root:root
    permissions: '0644'

# Run commands
runcmd:
  # Set timezone
  - timedatectl set-timezone Europe/Paris

  # Install Docker CE
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

  # Configure UFW firewall
  - ufw --force enable
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow 22/tcp comment 'SSH'
  - ufw allow 80/tcp comment 'HTTP'
  - ufw allow 443/tcp comment 'HTTPS'

  # Create deployment directory
  - mkdir -p /home/deploy/izzzi
  - chown -R deploy:deploy /home/deploy/izzzi

  # Add deploy user to docker group
  - usermod -aG docker deploy

  # Restart Docker to apply configuration
  - systemctl daemon-reload
  - systemctl restart docker
  - systemctl enable docker

  # Final system update
  - apt-get autoremove -y
  - apt-get autoclean

final_message: "IZZZI Docker Compose server initialization completed successfully at $(date)"
